name: Build SMS Image
on:
  push:
    branches:
      - "main"

env:
  IMAGE_NAME: "ochom/dobu-sms:latest"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Build
        working-directory: ./sms
        run: docker build -t ${{env.IMAGE_NAME}} .

      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push to Docker Hub
        run: docker push ${{env.IMAGE_NAME}}
